
    create table custom_field_definitions (
        field_order integer not null,
        group_id bigint not null,
        id bigint generated by default as identity,
        label varchar(255) not null,
        type varchar(255) not null check ((type in ('TEXT','NUMBER','DATE','SELECT','CHECKBOX'))),
        validations jsonb,
        primary key (id)
    );

    create table custom_field_groups (
        group_order integer not null,
        id bigint generated by default as identity,
        tenant_id uuid not null,
        module varchar(255) not null check ((module in ('DRESS','DRESS_MOVEMENT'))),
        name varchar(255) not null,
        primary key (id)
    );

    create table custom_field_values (
        definition_id bigint not null,
        id bigint generated by default as identity,
        target_id bigint not null,
        value varchar(1000) not null,
        primary key (id),
        unique (definition_id, target_id)
    );

    create table dress_movement (
        quantity integer,
        dress_id bigint not null,
        id bigint generated by default as identity,
        instant timestamp(6) with time zone,
        tenant_id uuid not null,
        primary key (id)
    );

    create table dresses (
        price numeric(10,2),
        stock integer not null,
        color VARCHAR(7) CHECK (color ~* '^#[0-9a-f]{6}$' OR color IS NULL),
        id bigint generated by default as identity,
        tenant_id uuid not null,
        size varchar(64),
        sku varchar(64) not null,
        title varchar(150) not null,
        primary key (id),
        unique (sku, tenant_id)
    );

    create table tenant_modules (
        tenant_id uuid not null,
        module_type varchar(255) not null check ((module_type in ('DRESS','DRESS_MOVEMENT'))),
        primary key (tenant_id, module_type)
    );

    create table tenants (
        has_custom_fields boolean not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id uuid not null,
        name varchar(120) not null unique,
        primary key (id)
    );

    create table user_allowed_tenants (
        user_id bigint not null,
        tenant_id uuid not null,
        primary key (user_id, tenant_id)
    );

    create table users (
        id bigint generated by default as identity,
        tenant_id uuid not null,
        username varchar(120) not null unique,
        auth0_sub varchar(255) unique,
        role varchar(255) not null check ((role in ('SUPERADMIN','RESELLER','ADMIN','USER'))),
        primary key (id)
    );

    alter table if exists custom_field_definitions 
       add constraint FKrud3dptqvg6i4l8uinggr055j 
       foreign key (group_id) 
       references custom_field_groups 
       on delete cascade;

    alter table if exists custom_field_groups 
       add constraint FK8axeq2583l5ps0170tht56jsm 
       foreign key (tenant_id) 
       references tenants 
       on delete cascade;

    alter table if exists custom_field_values 
       add constraint FK1fmnevwta0govxsh09p140wa0 
       foreign key (definition_id) 
       references custom_field_definitions 
       on delete cascade;

    alter table if exists dress_movement 
       add constraint FKqe45v10y8a3cynfrsphbjfx8q 
       foreign key (tenant_id) 
       references tenants 
       on delete cascade;

    alter table if exists dress_movement 
       add constraint FK6ktow90tpjwt1ei515oeouqaf 
       foreign key (dress_id) 
       references dresses 
       on delete cascade;

    alter table if exists dresses 
       add constraint FKly3dgkjpddgjow5qsyiowra12 
       foreign key (tenant_id) 
       references tenants 
       on delete cascade;

    alter table if exists tenant_modules 
       add constraint FKdwmiswv7wrjahbvwhj2l0k6kk 
       foreign key (tenant_id) 
       references tenants;

    alter table if exists user_allowed_tenants 
       add constraint FK90t8mnrq6deeenkawsmxigjw0 FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;

    alter table if exists user_allowed_tenants 
       add constraint FKd7n5j6imrobxhrlr4iecb0h25 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

    alter table if exists users 
       add constraint FK21hn1a5ja1tve7ae02fnn4cld 
       foreign key (tenant_id) 
       references tenants 
       on delete cascade;

    create table custom_field_definitions (
        field_order integer not null,
        group_id bigint not null,
        id bigint generated by default as identity,
        label varchar(255) not null,
        type varchar(255) not null check ((type in ('TEXT','NUMBER','DATE','SELECT','CHECKBOX'))),
        validations jsonb,
        primary key (id)
    );

    create table custom_field_groups (
        group_order integer not null,
        id bigint generated by default as identity,
        tenant_id uuid not null,
        module varchar(255) not null check ((module in ('DRESS','DRESS_MOVEMENT'))),
        name varchar(255) not null,
        primary key (id)
    );

    create table custom_field_values (
        definition_id bigint not null,
        id bigint generated by default as identity,
        target_id bigint not null,
        value varchar(1000) not null,
        primary key (id),
        unique (definition_id, target_id)
    );

    create table dress_movement (
        quantity integer,
        dress_id bigint not null,
        id bigint generated by default as identity,
        instant timestamp(6) with time zone,
        tenant_id uuid not null,
        primary key (id)
    );

    create table dresses (
        price numeric(10,2),
        stock integer not null,
        color VARCHAR(7) CHECK (color ~* '^#[0-9a-f]{6}$' OR color IS NULL),
        id bigint generated by default as identity,
        tenant_id uuid not null,
        size varchar(64),
        sku varchar(64) not null,
        title varchar(150) not null,
        primary key (id),
        unique (sku, tenant_id)
    );

    create table tenant_modules (
        tenant_id uuid not null,
        module_type varchar(255) not null check ((module_type in ('DRESS','DRESS_MOVEMENT'))),
        primary key (tenant_id, module_type)
    );

    create table tenants (
        has_custom_fields boolean not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id uuid not null,
        name varchar(120) not null unique,
        primary key (id)
    );

    create table user_allowed_tenants (
        user_id bigint not null,
        tenant_id uuid not null,
        primary key (user_id, tenant_id)
    );

    create table users (
        id bigint generated by default as identity,
        tenant_id uuid not null,
        username varchar(120) not null unique,
        auth0_sub varchar(255) unique,
        role varchar(255) not null check ((role in ('SUPERADMIN','RESELLER','ADMIN','USER'))),
        primary key (id)
    );

    alter table if exists custom_field_definitions 
       add constraint FKrud3dptqvg6i4l8uinggr055j 
       foreign key (group_id) 
       references custom_field_groups 
       on delete cascade;

    alter table if exists custom_field_groups 
       add constraint FK8axeq2583l5ps0170tht56jsm 
       foreign key (tenant_id) 
       references tenants 
       on delete cascade;

    alter table if exists custom_field_values 
       add constraint FK1fmnevwta0govxsh09p140wa0 
       foreign key (definition_id) 
       references custom_field_definitions 
       on delete cascade;

    alter table if exists dress_movement 
       add constraint FKqe45v10y8a3cynfrsphbjfx8q 
       foreign key (tenant_id) 
       references tenants 
       on delete cascade;

    alter table if exists dress_movement 
       add constraint FK6ktow90tpjwt1ei515oeouqaf 
       foreign key (dress_id) 
       references dresses 
       on delete cascade;

    alter table if exists dresses 
       add constraint FKly3dgkjpddgjow5qsyiowra12 
       foreign key (tenant_id) 
       references tenants 
       on delete cascade;

    alter table if exists tenant_modules 
       add constraint FKdwmiswv7wrjahbvwhj2l0k6kk 
       foreign key (tenant_id) 
       references tenants;

    alter table if exists user_allowed_tenants 
       add constraint FK90t8mnrq6deeenkawsmxigjw0 FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;

    alter table if exists user_allowed_tenants 
       add constraint FKd7n5j6imrobxhrlr4iecb0h25 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

    alter table if exists users 
       add constraint FK21hn1a5ja1tve7ae02fnn4cld 
       foreign key (tenant_id) 
       references tenants 
       on delete cascade;
